services:
  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../alert-rules.prometheus.yml:/etc/prometheus/alert-rules.prometheus.yml:ro
    depends_on:
      - blackbox-exporter
      - alertmanager

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    command:
      - --config.file=/etc/blackbox_exporter/blackbox.yml
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml:ro

  alertmanager:
    image: prom/alertmanager:v0.27.0
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
